### ISSUE TITLE
新版本libloader无法加载

### ISSUE THREAD

**Issue by lesser0** [Nambers/MiraiCP#149]
### Code of Conduct

- [X] I conform

### 问题描述

2.12.0-RC2正常，至少2.13.0-alpha起在部分机器上无法加载libloader。即使是在同一台机器上编译的libloader同样无法加载。

### 日志

```text
2022-11-21 02:06:28 E/MiraiCP: java.lang.UnsatisfiedLinkError: C:\mirai_update\libLoader.dll: 找不到指定的程序。
java.lang.UnsatisfiedLinkError: C:\mirai_update\libLoader.dll: 找不到指定的程序。
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
        at java.base/java.lang.Runtime.load0(Runtime.java:785)
        at java.base/java.lang.System.load(System.java:1979)
        at MiraiCP-plugin-2.13.0-alpha-3.mirai2.jar//tech.eritquearcus.miraicp.shared.CPPLibMultiplatform.init(CPPLibMultiplatform.kt:34)
        at MiraiCP-plugin-2.13.0-alpha-3.mirai2.jar//tech.eritquearcus.miraicp.shared.CPPLib.init(CPPLib.kt:42)
        at MiraiCP-plugin-2.13.0-alpha-3.mirai2.jar//tech.eritquearcus.miraicp.shared.CPPLib.init$default(CPPLib.kt:36)
        at MiraiCP-plugin-2.13.0-alpha-3.mirai2.jar//tech.eritquearcus.miraicp.PluginMain.onEnable(PluginMain.kt:83)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:305)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:175)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:336)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
```

### 版本

v2.13.0-alpha 及以上

### 组件

LibLoader

### 编译器

Microsoft Visual C++ (MSVC)

### 系统

Windows

### 架构

x86-64/amd64

**Comment by Antares0982** [comment]
https://github.com/0ph1uch1/MiraiCP-debug-docs/releases/tag/v2.13.0-alpha-3 先使用MinGW build，之后尝试降低CI工具链为vs2017以及低版本Windows SDK

**Comment by Antares0982** [comment]
https://github.com/actions/runner-images/issues/35 https://github.com/actions/runner-images/issues/3294
目前已经没有workflow镜像还有vs2017。CI将使用vs2019及以上版本
