### ISSUE TITLE
收到大量消息时，在MCL使用MiraiCP插件时收到消息存在严重延迟且发送消息后报错

### ISSUE THREAD

**Issue by Antarcticann** [Nambers/MiraiCP#76]
**Describe the bug 描述出现的异常(实际行为和预期行为)**
插件确定没有问题，在我自己的电脑使用只添加了一个群和两三个好友的小号进行测试，发送群聊消息延迟在3s左右，发送私聊消息延迟在1s以内
此时有一个问题：mcl偶尔会卡主，表现为在某个时间点突然收不到消息，然后再mcl窗体随意输入任何字符的那一瞬间，没有收到的消息突然就刷出来，且显示接收时间相同（实际上这些消息在QQ上并不是同时发送的），这个问题在测试时出现频率较低且没什么规律。

插件在小号上测试完毕后我在mcl上登陆了一个bot，加的群比较多，大约有500+群，消息大概每秒三四条。此时问题开始出现，我在群里发送消息后大概半分钟甚至更长时间后这条消息才显示在mcl界面上，有时还会丢失这条消息。
而在性能较低的服务器上有时一分钟以上才能接收到消息
而在接收到消息后，发送消息时那个问题又出现了。下面是其中的一次的情况，这个问题很容易复现，如果还需要其他例子，我可以提供。
**Screenshots 相关代码和日志截图或复制上来**
2021-08-23 16:18:06 V/Bot.3457317465: [H*****b(9*****4)] 不*****盟）(4*****2) -> .ct
（这条消息其实是我在16:17:32时发送的）
2021-08-23 16:18:08 I/MiraiCP: Send message for Group(9*****4) is 品味生活！已为不*****盟）调好最合适的饮品：
Mimosa（含羞草） 6.50%Vol.
世上有多少种水果，就有多少种含羞草
开胃，发泡，清爽
描述仅供参考
2021-08-23 16:18:08 V/Bot.3*****5: Event: GroupMessagePreSendEvent(target=Group(9*****4), message=品味生活！已为不 *****盟）调好最合适的饮品：
Mimosa（含羞草） 6.50%Vol.
世上有多少种水果，就有多少种含羞草
开胃，发泡，清爽
描述仅供参考)
2021-08-23 16:18:09 V/Bot.3*****5: [犬*****厅(1*****0)] F*****k(3*****8) -> [mirai:image:{C4616713-4CD1-0616-FB55-99EC6FC9CC64}.jpg]
2021-08-23 16:18:13 V/Bot.3*****5: Event: Dropped(bot=Bot(3*****5), cause=HeartbeatFailedException: AliveHeartbeat, recoverable=true, cause=PacketTimeoutException(message=Timeout receiving Heartbeat response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms))
2021-08-23 16:18:14 V/Bot.3*****5: [沈*****锤(1*****6)] 反*****徒(1*****7) -> 两个6联旋风热熔
2021-08-23 16:18:18 V/Bot.3*****5: [被*****）(6*****2)] 加*****子(1*****8) -> [mirai:quote:[1*****7],[1*****8]][mirai:at:5*****8] 问题不大，群里比你怪的也有
2021-08-23 16:18:18 V/Bot.3*****5: Group(9*****4) <- 品味生活！已为不*****盟）调好最合适的饮品：\nMimosa（含羞草） 6.50%Vol.\n世上有多少种水果，就有多少种含羞草\n开胃，发泡，清爽\n描述仅供参考
2021-08-23 16:18:18 W/Bot.3*****5: Connection lost, reconnecting... (HeartbeatFailedException: AliveHeartbeat, recoverable=true, cause=PacketTimeoutException(message=Timeout receiving Heartbeat response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms))
2021-08-23 16:18:18 V/Bot.3*****5: Event: GroupMessagePostSendEvent(target=Group(9*****4), message=品味生活！已为不*****盟）调好最合适的饮品：
Mimosa（含羞草） 6.50%Vol.
世上有多少种水果，就有多少种含羞草
开胃，发泡，清爽
描述仅供参考, exception=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms, receipt=null)
2021-08-23 16:18:18 I/stdout: Timed out waiting for 5000 ms
2021-08-23 16:18:18 I/stdout: {"data":{"miraiCode":false,"source":"{\"contact\":{\"botid\":3*****5,\"groupid\":0,\"id\":9*****4,\"nickornamecard\":\"H*****b\",\"type\":2},\"content\":\"品味生活！已为不*****盟）调好最 合适的饮品：\\nMimosa（含羞草） 6.50%Vol.\\n世上有多少种水果，就有多少种含羞草\\n开胃，发泡，清爽\\n描述仅供参考\"}"},"type":1}
2021-08-23 16:18:18 W/stderr: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
2021-08-23 16:18:18 W/stderr:   at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
2021-08-23 16:18:18 W/stderr:   at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
2021-08-23 16:18:18 W/stderr:   at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
2021-08-23 16:18:18 W/stderr:   at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
2021-08-23 16:18:18 W/stderr:   at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
2021-08-23 16:18:18 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)
2021-08-23 16:18:18 E/MiraiCP: MiraiCP error:MiraiCP内部无法预料的错误:reach a error area, Contact::SendMiraiCode
2021-08-23 16:18:18 V/Bot.3*****5: [C*****组(7*****3)] 群*****往(8*****8) -> 也可能大家只看见一张嘴连着个胃？
2021-08-23 16:18:18 I/Bot.3*****5: Saved account secrets to local cache for fast login.
2021-08-23 16:18:18 I/Bot.3*****5: Login successful.
2021-08-23 16:18:18 V/Bot.3*****5: Event: BotOnlineEvent(bot=Bot(3*****5))
2021-08-23 16:18:18 I/Bot.3*****5: LMT白名单读取完成
2021-08-23 16:18:18 I/Bot.3*****5: LMT列表读取完成
2021-08-23 16:18:18 I/Bot.3*****5: 全局昵称读取完成
2021-08-23 16:18:18 I/Bot.3*****5: 群组昵称读取完成
2021-08-23 16:18:18 I/Bot.3*****5: 关闭群列表读取完成
2021-08-23 16:18:18 I/Bot.3*****5: 村规读取完成
2021-08-23 16:18:18 I/Bot.3*****5: 目前以名称检索的酒品名单上的酒品分别有这么多：157 157
2021-08-23 16:18:18 V/Bot.3*****5: Event: BotReloginEvent(bot=Bot(3*****5), cause=null)
2021-08-23 16:18:18 I/Bot.3*****5: Reconnected successfully in 0.287s.
2021-08-23 16:18:19 V/Bot.3*****5: [庸*****团(8*****3)] 本*****红(2*****0) -> 稳妥=委托
**Desktop (please complete the following information): 描述本地运行环境**
版本:
 - [ 2.7RCdev5] plugin
 - [ 2.7RCdev5] loader
 - MiraiCP版本: `v 2.7RCdev5`

感谢大佬！
第一次发issues，如果有哪里有问题我会立刻修改的！

**Comment by Nambers** [comment]
大概代码里面涉及了哪些操作? 就发送信息之类的?
或者有没有涉及到耗时操作，如读写文件

**Comment by Antarcticann** [comment]
.ct这个功能就只是从一个map里随机取出一个元素然后sendMsg，大佬可以在这里查看插件的代码https://github.com/Antarcticann/Dice_Qingmulian_ForMirai_CP

**Comment by Nambers** [comment]
@Antarcticann 我试了下，从Kt发布事件到cpp接受到事件要2s, 然后10次sendMsg的平均值是190ms, sendMiraiCode是199ms, 从cpp返回到kt要1ms, 然后我找不到复现你那个timeOut报错的方法，报错没说是在哪报的错
大量信息涌入我有时间去测一遍
然后如果可以的话 能不能发一下编译后的dll 我看看能不能复现timeOut错误

**Comment by Antarcticann** [comment]
当然可以！您可以在这里直接下载dll，另外如果有需要的话我也可以直接用QQ的共享桌面给您看x
https://github.com/Antarcticann/Dice_Qingmulian_ForMirai_CP/releases/tag/v0.1-pre_alpha

**Comment by Nambers** [comment]
@Antarcticann 
日志里出现了Dropped(就是BotOfflineEvent)和reLogin Event，可能是网络问题?
这种情况是可以复现吗, 就出现了不只一次?

**Comment by Antarcticann** [comment]
是的，可以复现，有的时候开机十多分钟就报错好几次，只登录机器人，不加载插件的时候就不报错，大概不是网络的问题

**Comment by Nambers** [comment]
okok

**Comment by Antarcticann** [comment]
错误基本上是在接收到命令之后，发送消息的时候触发的，开机如果没有接受到任何指令的话，触发频率很低，我正在回家的路上，我可以回家之后再统计一下报错的情况发给您！

**Comment by Antarcticann** [comment]
消息发送时的报错报错基本上都是TimeOut，开机时的报错请让我再复现一遍看看

**Comment by Nambers** [comment]
okok TimeOut的话我一般没怎么遇到 一般来说我觉得应该是网络问题貌似，因为timeOut是mirai端抛出的
一般而言sendMessage抛出timeOutException就是服务器无响应

**Comment by Antarcticann** [comment]
我刚才在服务器挂了半个小时，错误大概被触发了二十多次，在统计报错的时候，我对这个错误的发生有了一个存在于可能性的猜想。
我的服务器性能并不强劲，CPU是AMDGX218GL SOC，双核1.8GHz；但是不至于无法运行骰子，之前使用的酷Q和XQ都运行的很流畅，而XQ则到现在仍然在正常运行中（就是同一个bot并且使用了相同的插件
在我统计bug的过程中，我注意到随着mirai运行时间的延长，从QQ发送消息到消息显示在MCL窗体上，这之间的时间延迟越来越长。从最开始的只有一两秒，到后面的几分钟，直到我强制停止MCL之前接受到的一条消息，延迟已经达到了可怕的6分钟

> 实际上这句话是我在18:08:11时发送的
> 2021-08-25 18:14:11 V/Bot.3457317465: [H——b(9——4)] 不——盟(4——2) -> 先别说话，我看看 延迟有多少

而我注意到刚启动bot的时候，收到的指令是能正常发送的，从某个时间点开始，收到的消息在发送之后就会弹出TimeOut报错

> 2021-08-25 18:05:08 V/Bot.3——5: [H——b(9——4)] 不——盟(4——2) -> .ct
> 2021-08-25 18:05:10 I/MiraiCP: Send message for Group(9——4) is 品味生活！已为不——盟调好最合适的饮品：
> Orgasm（高潮） 21.25%Vol.
> 又叫做Shooter，你明白的
> 甜，香，微凉
> 描述仅供参考
> 2021-08-25 18:05:10 V/Bot.3——5: Event: GroupMessagePreSendEvent(target=Group(9——4), message=品味生活！已为不 ——盟调好最合适的饮品：
> Orgasm（高潮） 21.25%Vol.
> 又叫做Shooter，你明白的
> 甜，香，微凉
> 描述仅供参考)
> 2021-08-25 18:05:20 V/Bot.3——5: Group(9——4) <- 品味生活！已为不是柴刀（不改矬子联盟）调好最合适的饮品：\nOrgasm（高潮） 21.25%Vol.\n又叫做Shooter，你明白的\n甜，香，微凉\n描述仅供参考
> 2021-08-25 18:05:20 V/Bot.3——5: Event: GroupMessagePostSendEvent(target=Group(9——4), message=品味生活！已为不是柴刀（不改矬子联盟）调好最合适的饮品：
> Orgasm（高潮） 21.25%Vol.
> 又叫做Shooter，你明白的
> 甜，香，微凉
> 描述仅供参考, exception=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms, receipt=null)
> 2021-08-25 18:05:20 I/stdout: Timed out waiting for 5000 ms
> 2021-08-25 18:05:20 I/stdout: {"data":{"miraiCode":false,"source":"{\"contact\":{\"botid\":3——5,\"groupid\":0,\"id\":9——4,\"nickornamecard\":\"H——b\",\"type\":2},\"content\":\"品味生活！已为不——盟调好最 合适的饮品：\\nOrgasm（高潮） 21.25%Vol.\\n又叫做Shooter，你明白的\\n甜，香，微凉\\n描述仅供参考\"}"},"type":1}
> 2021-08-25 18:05:20 W/stderr: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
> 2021-08-25 18:05:20 W/stderr:   at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
> 2021-08-25 18:05:20 W/stderr:   at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
> 2021-08-25 18:05:20 W/stderr:   at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
> 2021-08-25 18:05:20 W/stderr:   at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
> 2021-08-25 18:05:20 W/stderr:   at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
> 2021-08-25 18:05:20 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)
> 2021-08-25 18:05:20 E/MiraiCP: MiraiCP error:MiraiCP内部无法预料的错误:reach a error area, Contact::SendMiraiCode

从指令出现在MCL窗体上到插件处理完事件并且调用sendMsg之间只相差几十毫秒，而且几乎所有的消息都存在逐渐正常的延迟。
由此我得到一个猜测，可能是**mcl收到消息到并将消息传递到插件的过程的延时**超出了一个**由传递事件与消息间隔决定的阈值**，导致在**大量信息输入的情况下每条信息尚未处理结束就又传入了下一个信息，最终恶性循环使从接收到消息到处理消息的延时变得越来越长，也就是说消息被积压了**，最终在积压时间超过一个值时，由于接收到消息到发送回应消息之间的时间间隔太长，触发了TimeOut错误，导致消息发送失败。
这只是我的猜测，我对Mirai内部运作的过程并不十分了解，希望大佬能找到这个错误的真正原因

另外，在login结束，插件开始运行后，还出现了一个其他类型的报错，我也把它贴在这里了，它只出现了1次

> 2021-08-25 17:56:51 V/Bot.3——5: [坑——营(3——7)] 电——蟹(1——0) -> 点开那个流泪猫猫头
> 2021-08-25 17:56:51 V/Bot.3——5: [西——厨(9——1)] 历——Z(2——6) -> [mirai:origin:FORWARD,hCjsC8vl26gXVoSl/TnkiQ4iku0jxxMTMPzgxf7fxei87PdIHhH7NPDQ7IF/xBga]ForwardMessage(preview=[小——町:[动画表情], 小——町:[ 视频消息], 小——町:[动画表情][图片][图片][图片], 小——町:[动画表情]], title=群聊的聊天记录, brief=[聊天记录], source=聊天记录, summary=查看转发消息, nodeList=[Node(senderId=3——8, time=1629858664, senderName=小——町, messageChain=[mirai:image:{D10DF2FE-75AD-77D1-1195-A226145E6B18}.mirai]), Node(senderId=3——8, time=1629872814, senderName=小——町, messageChain=你的QQ暂不支持查看视频短片，请期待后续版本。[不支持的消息#660619550]), Node(senderId=3——8, time=1629872815, senderName=小——町, messageChain=[mirai:image:{6754A11B-1CE7-5DF9-8799-DAB9927D6D9E}.mirai][mirai:image:{0CA1FDD6-EE28-0A05-342A-E2A1C9FADB97}.mirai][mirai:image:{D218220D-A31C-5BA4-5C70-F6AD68568746}.mirai][mirai:image:{8438DEE6-47CE-844F-7954-EC0C638B75A2}.mirai]), Node(senderId=3——8, time=1629879506, senderName=小——町, messageChain=[mirai:image:{309E29BC-34A5-D554-58E8-29FC01FB6BE5}.mirai])])
> 2021-08-25 17:56:51 E/miraiCP: Exception in coroutine Plugin miraiCP of miraiCP
> kotlinx.serialization.SerializationException: Class 'ForwardMessageInternal' is not registered for polymorphic serialization in the scope of 'SingleMessage'.
> Mark the base class as 'sealed' or register the serializer explicitly.
>         at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
>         at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:113)
>         at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:96)
>         at kotlinx.serialization.json.internal.PolymorphicKt.findActualSerializer(Polymorphic.kt:29)
>         at kotlinx.serialization.json.internal.PolymorphicKt.access$findActualSerializer(Polymorphic.kt:1)
>         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:214)
>         at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
>         at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:69)
>         at net.mamoe.mirai.message.data.MessageChain$Serializer.serialize(MessageChain.kt:266)
>         at net.mamoe.mirai.message.data.MessageChain$Serializer.serialize(MessageChain.kt:261)
>         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:211)
>         at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
>         at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData$$serializer.serialize(MessageSerializersImpl.kt:41)
>         at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData$$serializer.serialize(MessageSerializersImpl.kt:41)
>         at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$special$$inlined$map$1.serialize(Serialization.kt:70)
>         at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl.serialize(MessageSerializersImpl.kt)
>         at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl.serialize(MessageSerializersImpl.kt:28)
>         at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:211)
>         at kotlinx.serialization.json.Json.encodeToString(Json.kt:80)
>         at tech.eritquearcus.miraicp.shared.PublicShared$onEnable$2.invokeSuspend(PublicShared.kt:770)
>         at tech.eritquearcus.miraicp.shared.PublicShared$onEnable$2.invoke(PublicShared.kt)
>         at tech.eritquearcus.miraicp.shared.PublicShared$onEnable$2.invoke(PublicShared.kt)
>         at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:432)
>         at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
>         at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
>         at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
>         at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
>         at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
>         at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
>         at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
>         at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
>         at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:160)
>         at net.mamoe.mirai.internal.event.InternalEventListenersKt.callAndRemoveIfRequired(InternalEventListeners.kt:109)
>         at net.mamoe.mirai.event._EventBroadcast.broadcastImpl(Event.kt:174)
>         at net.mamoe.mirai.IMirai.broadcastEvent(IMirai.kt:312)
>         at net.mamoe.mirai.internal.MiraiImpl.broadcastEvent$suspendImpl(MiraiImpl.kt:304)
>         at net.mamoe.mirai.internal.MiraiImpl.broadcastEvent(MiraiImpl.kt)
>         at net.mamoe.mirai.event._EventBroadcast.broadcastPublic$suspendImpl(Event.kt:161)
>         at net.mamoe.mirai.event._EventBroadcast.broadcastPublic(Event.kt)
>         at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:148)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$2.invokeSuspend(EventDispatcher.kt:90)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$2.invoke(EventDispatcher.kt)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$2.invoke(EventDispatcher.kt)
>         at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
>         at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast$suspendImpl(EventDispatcher.kt:89)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast(EventDispatcher.kt)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcastAsync$job$1.invokeSuspend(EventDispatcher.kt:105)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcastAsync$job$1.invoke(EventDispatcher.kt)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcastAsync$job$1.invoke(EventDispatcher.kt)
>         at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
>         at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
>         at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
>         at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
>         at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcastAsync-kKe4JaQ(EventDispatcher.kt:102)
>         at net.mamoe.mirai.internal.network.components.EventDispatcher.broadcastAsync-kKe4JaQ$default(EventDispatcher.kt:35)
>         at net.mamoe.mirai.internal.network.components.EventBroadcasterPacketHandler.impl(PacketHandler.kt:87)
>         at net.mamoe.mirai.internal.network.components.EventBroadcasterPacketHandler.handlePacket(PacketHandler.kt:73)
>         at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
>         at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
>         at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
>         at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
>         at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
>         at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
>         at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
>         at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
>         at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
>         at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
>         at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:82)
>         at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:186)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
>         at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
>         at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
>         at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
>         at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
>         at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
>         at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
>         at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
>         at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
>         at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
>         at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
>         at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
>         at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Antarcticann** [comment]
“逐渐正常”应为“逐渐增长”

**Comment by Antarcticann** [comment]
再补充一下
之前我说有的消息收不到只是表象，实际上每条消息都能收到，但由于延迟太长我没能看到消息
另外，在消息延迟严重的时候，在mcl窗体输入/stop时，mcl没有任何回应

**Comment by Nambers** [comment]
okok 我写个测试框架有时间测试一下高并发下的问题

**Comment by Antarcticann** [comment]
大佬加油！！！！！＼(＞０＜)／
